[package]
name = "lba2sd"
version = "1.0.0"
edition = "2021"
authors = ["Melechtna Antelecht <Melechtna@gmail.com>"]

[dependencies]
clap = "4.5.4"
bytemuck = "1.15.0"

[[bin]]
name = "lba2sd"
path = "src/main.rs"
